sudo: false
language: ruby
rvm:
  - "2.3.7"
cache: bundler
bundler_args: --retry=6
script:
  - bundle exec rspec
notifications:
  email: false
before_install:
  - gem install bundler
env:
  - "RAILS_VERSION=5.2.4.3"
  - "RAILS_VERSION=6.0.3"
